import fs from "fs";
import path from "path";
import type { CalendarEvent, Transaction } from "./types";

export interface Customer {
  id: string;
  household: "single" | "couple" | "family";
  ageBand: "18-29" | "30-44" | "45-64" | "65+";
  region: string;
  city: string;
  products: Record<string, boolean>;
}

export interface PastMoment {
  type: string;
  customerId: string;
  household: string;
  ageBand: string;
  region: string;
  country?: string;
  city?: string;
  nights?: number;
  totalSpent?: number;
  unexpectedCost?: number;
  extraCostsFirst3Months?: number;
  giftAmount?: number;
  forgot: string[];
}

/** A demo customer who can log in. Generated by scripts/generate.py. */
export interface Persona extends Customer {
  name: string;
  age: number;
  passwordHash: string; // bcrypt
  calendar: CalendarEvent[];
  transactions: Transaction[];
}

const dataDir = path.join(process.cwd(), "data");
const templatesDir = path.join(process.cwd(), "templates");

// Files are read once and kept in memory; the data is static during a demo.
const cache = new Map<string, unknown>();

function readJson<T>(file: string, fallback: T): T {
  if (!cache.has(file)) {
    cache.set(file, fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, "utf-8")) : fallback);
  }
  return cache.get(file) as T;
}

export function getCustomers(): Customer[] {
  return readJson(path.join(dataDir, "customers.json"), []);
}

export function getPastMoments(): PastMoment[] {
  return readJson(path.join(dataDir, "past_moments.json"), []);
}

export function getPersonas(): Persona[] {
  return readJson(path.join(dataDir, "personas.json"), []);
}

export function findPersona(id: string): Persona | undefined {
  return getPersonas().find((p) => p.id === id);
}

export function getTemplate(type: string): any {
  if (!/^[a-z_]+$/.test(type)) return null; // only known moment types map to files
  return readJson(path.join(templatesDir, `${type}.json`), null);
}
